PAYLOADPATH="./Payload"
APPPATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"
IPANAME="${TARGET_NAME}.ipa"
IPAPATH="${HOME}/Desktop/${IPANAME}"

rm -rf $PAYLOADPATH
mkdir -p $PAYLOADPATH
cp -r $APPPATH $PAYLOADPATH
# rm -rf $IPAPATH
# zip -r $IPAPATH $PAYLOADPATH
# zip -r $IPAPATH $PAYLOADPATH
# cd "$PAYLOADPATH/.."
zip -qr $IPANAME $PAYLOADPATH
rm -rf $PAYLOADPATH